Merge Develop branch into Master (#1)
* moveit_servo: added publisher that streams servo calculated distance to collision in meters

* moveit_servo: start MoveIt's move_group planning scene monitor correctly.
- Joint state topic is set based on the input yaml parameter.
- Load octomap monitor

* added dependency to build on melodic

* corrected rosinstall

* backported ruckig trajectory smoothing from ros2

* added comments on how to add jerk limit reading

* planning_scene_interface: fix getKnownObjectNamesInROI function, before pose message relative to parent pose message was used as parent message.

* Added read jerk_limits from joint_limits.yaml

* included jerklimits structure inside namespace

* removed unnecesarry infos

* moveit_servo: modify moveit servo collision checking to take into account allowed collision matrix values during servoing.

* fix compilation issue -> error: 'make_unique' is not a member of 'std'

* moveit_servo: added servoing goal tolerances dynamic changing using ros topic for pose tracking mode

* trajectory_processing: fix planning error when planning to already reached goal position when using TOTG algorithm

---------

Co-authored-by: Marc Bosch-Jorge <marbosjo@users.noreply.github.com>
Co-authored-by: marbosjo <mbosch@robotnik.es>
Co-authored-by: Sandra Moreno <smoreno@robotnik.es>